config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :badges, only: [:index]
  resources :characters, only: [:index, :show]
  post '/characters/:id/add_badge', to: 'characters#add_badge_to_character', as: :add_badge_to_character
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/badge.rb
class Badge < ApplicationRecord
    has_many :character_badges
    has_many :characters, through: :character_badges

end

app/models/character.rb
require 'date'
require 'rest-client'
require 'base64'


class Character < ApplicationRecord
    has_many :character_badges
    has_many :badges, through: :character_badges

    def self.assign_new_badge(character_id, badge_id)
        @character = Character.find(character_id)
        @badge = Badge.find(badge_id)
        digits = (1..15000).to_a.sample
        email = "fake_email#{digits}@fake.com"
        issued_at = DateTime.now 

        if @character.name.split(' ').length == 1
            first_name = @character.name.split(' ')[0]
            last_name = 'Marvelous'
        else
            first_name = @character.name.split(' ')[0]
            last_name = @character.name.split(' ')[1]
        end
        
        badge_template_id = @badge.badge_id

        response_body = {
            "recipient_email": email,
            "issued_to_first_name": first_name,
            "issued_to_last_name": last_name,
            "badge_template_id": badge_template_id,
            "issued_at": issued_at,
            
          }

          auth = Base64.strict_encode64(ENV['CREDLY_AUTH'])

          credly_headers = {
            :Accept => "application/json",
            :Authorization => "Basic #{auth}",
            "Content-Type" => "application/json"
        }

 
          RestClient::Request.execute(method: :post, url: "https://sandbox-api.credly.com/v1/organizations/#{ENV['CREDLY_ORG_ID']}/badges", payload: response_body, headers: credly_headers)
    
          CharacterBadge.create(badge_id: badge_id, character_id: character_id, recipient_email: email, issued_to_first_name: first_name,  issued_to_last_name: last_name, badge_template_id: badge_template_id, issued_at: issued_at )

          @character
    end
end

app/models/character_badge.rb
class CharacterBadge < ApplicationRecord
    belongs_to :character
    belongs_to :badge
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController

    def index 
        @badges = Badge.all
    end

    def new 
        @badge = Badge.new 
    end

    def create 
        @badge = Badge.new(badge_params)

        if @badge.save
            redirect_to badge_path(@badge)
        else
            render :new 
        end
    end

    def show 
        @badge = Badge.find(params[:id])
    end

    private 

    def badge_params 
        params.require(:badge).permit(:badge_id, :name, :image_url, :issuer, :skill)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    def index 
        @characters = Character.all
    end

    def new 
        @character = Character.new 
    end

    def create 
        @character = Character.new(character_params)

        if @character.save
            redirect_to character_path(@character)
        else
            render :new 
        end
    end

    def show 
        @character = Character.find(params[:id])
    end

    def add_badge_to_character 
        redirect_to character_path(Character.assign_new_badge(params[:id], params[:badge_id]))
    end

    private 

    def character_params 
        params.require(:character).permit(:name, :image, :description)
    end
end

app/controllers/static_pages_controller.rb
# frozen_string_literal: true

class StaticPagesController < ApplicationController
  def home; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/badge_helper.rb
module BadgeHelper
end

app/helpers/character_badges_helper.rb
module CharacterBadgesHelper
end

app/helpers/character_helper.rb
module CharacterHelper
end

app/views/badges/index.html.erb
<%= stylesheet_link_tag 'badge_index.css'%>
<div class='badge_index_pg'>
        <div class='header-line'>
        <%= image_tag 'credly_logo.png', :class=>"header_img"%> 
        <h2>Available Badges - Assign Them To Heroes</h2>
        <h3 class='char_link'><%= link_to 'Character Selection', characters_path %></h3>
        </div>
    <div class='card_container'>
        <% @badges.each do |badge| %>
        <div class='card'>
            <%= image_tag badge.image_url %>
            <div class='card_description'>
            <h1>Badge Name: <%= badge.name %></h1>
            <h3>Issuing Organization: <%= badge.issuer %></h3>
            <h3>Skill: <%= badge.skill %></h3>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/characters/index.html.erb
<%= stylesheet_link_tag 'character_index.css'%>
<div class='char_index_pg'>
        <div class='header-line'>
        <%= image_tag 'marvel_heroes.png', :class=>"header_img"%> 
        </div>
    <div class='card_container'>
        <% @characters.each do |character| %>
        <div class='card'>
            <%= image_tag character.image%>
            <div class='card_description'>
            <h2><%= link_to character.name,  character, :class=>"show_page_link"%></h2>
            </div>
        </div>
        <% end %>
    </div>
</div>

app/views/characters/show.html.erb
<%= stylesheet_link_tag 'character_show.css'%>
<%= link_to 'Back', characters_path, :class=>'nav_links' %>
<div class='char_show_row'>
    <div class='char_show_column_1'>
      <%= image_tag @character.image, :class=> 'char_pic'%>
        <div class='character_info'>
            <strong>Name:</strong>
            <%= @character.name %>
        <br>
            <strong>Description:</strong>
            <%= @character.description %>
             <h4>Current Badges</h4>
            <% if @character.badges.length > 0%>
                <% @character.badges.each do |badge| %>
                <%= image_tag badge.image_url, :class=>'img_container' %>  
                    <% end %>

            <% else %>
                <p>Collect Some Badges To Display Here! </p>
            <% end %>
        </div>
    </div>

    <div class='char_show_column_2'>
        <h1>Available Badges </h1>
        <div class='card_container'>
                <% Badge.all.select{|badge| !@character.badges.include?(badge)}.each do |badge| %>

                <div class='card'>
                    <%= image_tag badge.image_url %>
                    <div class='card_description'>
                    <h1>Badge Name: <%= badge.name %></h1>
                    <h3>Issuing Organization: <%= badge.issuer %></h3>
                    <h3>Skill: <%= badge.skill %></h3>
                    <h2><%= button_to "Add #{badge.name} to #{@character.name}",  action: 'add_badge_to_character', params: {character_id: @character.id, badge_id: badge.id} %></h2>
                    </div>
                </div>
                <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Credly Take-home</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag "application" %>
    <%= stylesheet_pack_tag "application" %>
  </head>

  <body>
    <!-- load React header component instead -->
    <%#= javascript_pack_tag "credly_take_home_header" %>

    <%= yield %>
  </body>
</html>

app/views/static_pages/home.html.erb
<%= stylesheet_link_tag "home.css" %>
<div class='home_pg'>
<%= image_tag 'credly_logo.png', :class=>"header_img"%> 
<div class="home_links">
<h2><%= link_to 'View Available Badges', badges_path, :class=>"home_links" %></h2>
<h2><%= link_to 'View List of Heroes', characters_path, :class=>"home_links" %></h2>
</div>
</div>